"use client";

import GlobalState, { GlobalContext } from "@/context";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <div className="flex w-full h-screen overflow-y-scroll">
            <Sidebar />
            <div className="w-[98%] ml-[16%]">
              <Header />
              <main>
                <div className="mx-auto p-4 md:p-6 2xl:p-8">{children}</div>
              </main>
            </div>
          </div>
        </GlobalState>
      </body>
    </html>
  );
}
